package ru.creditregistry._2010.webservice.singleformat.request;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;

/**
 * Р?РЅС‚РµСЂС„РµР№СЃ РІРµР±-СЃРµСЂРІРёСЃР°
 *
 * This class was generated by Apache CXF 2.4.1
 * 2018-08-02T15:10:28.722+03:00
 * Generated source version: 2.4.1
 * 
 */
@WebService(targetNamespace = "http://creditregistry.ru/2010/webservice/SingleFormatService", name = "SingleFormatService")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface SingleFormatService {

    /**
     * РњРµС‚РѕРґ РїСЂРµРґРЅР°Р·РЅР°С‡РµРЅ РґР»СЏ РѕР±РЅРѕРІР»РµРЅРёСЏ РёРЅС„РѕСЂРјР°С†РёРё
     * 				Рѕ СЃС‚Р°С‚СѓСЃР°С… РєСЂРµРґРёС‚РЅС‹С… Р·Р°СЏРІРѕРє
     */
    @WebMethod(action = "http://creditregistry.ru/2010/webservice/SingleFormatService/statusUpdate")
    @Action(input = "http://creditregistry.ru/2010/webservice/SingleFormatService/statusUpdate", output = "http://creditregistry.ru/2010/webservice/SingleFormatService/statusUpdateResponse")
    @WebResult(name = "ProcessRequestOut", targetNamespace = "http://creditregistry.ru/2010/webservice/SingleFormatService", partName = "joinedReport")
    public ProcessRequestOut statusUpdate(
        @WebParam(partName = "authData", name = "AuthData", targetNamespace = "http://creditregistry.ru/2010/webservice/SingleFormatService")
        AuthData authData,
        @WebParam(partName = "requestData", name = "StatusUpdateData", targetNamespace = "http://creditregistry.ru/2010/webservice/SingleFormatService")
        StatusUpdateData requestData
    );

    /**
     * РњРµС‚РѕРґ РѕСЃСѓС‰РµСЃС‚РІР»СЏРµС‚ Р·Р°РїСЂРѕСЃ Рє СѓРєР°Р·Р°РЅРЅРѕРјСѓ Р‘РљР? Рё
     * 				РІС‹РґР°РµС‚ РѕС‚РІРµС‚ РІ Р•РґРёРЅРѕРј С„РѕСЂРјР°С‚Рµ
     */
    @WebMethod(action = "http://creditregistry.ru/2010/webservice/SingleFormatService/processRequest")
    @Action(input = "http://creditregistry.ru/2010/webservice/SingleFormatService/processRequest", output = "http://creditregistry.ru/2010/webservice/SingleFormatService/processRequestResponse")
    @WebResult(name = "ProcessRequestOut", targetNamespace = "http://creditregistry.ru/2010/webservice/SingleFormatService", partName = "report")
    public ProcessRequestOut processRequest(
        @WebParam(partName = "authData", name = "AuthData", targetNamespace = "http://creditregistry.ru/2010/webservice/SingleFormatService")
        AuthData authData,
        @WebParam(partName = "requestData", name = "ProcessRequestData", targetNamespace = "http://creditregistry.ru/2010/webservice/SingleFormatService")
        ProcessRequestData requestData
    );

    @WebMethod(action = "http://creditregistry.ru/2010/webservice/SingleFormatService/groupRequestWSI")
    @Action(input = "http://creditregistry.ru/2010/webservice/SingleFormatService/groupRequestWSI", output = "http://creditregistry.ru/2010/webservice/SingleFormatService/groupRequestWSIResponse")
    @WebResult(name = "ProcessRequestOut", targetNamespace = "http://creditregistry.ru/2010/webservice/SingleFormatService", partName = "joinedReport")
    public ProcessRequestOut groupRequestWSI(
        @WebParam(partName = "requestData", name = "GroupRequestData", targetNamespace = "http://creditregistry.ru/2010/webservice/SingleFormatService")
        GroupRequestData requestData
    );

    /**
     * РњРµС‚РѕРґ РѕСЃСѓС‰РµСЃС‚РІР»СЏРµС‚ СЃРІРµРґРµРЅРёРµ РЅРµСЃРєРѕР»СЊРєРёС…
     * 				РѕС‚С‡С‘С‚РѕРІ, РѕР±СЉРµРґРёРЅС‘РЅРЅС‹С… РµРґРёРЅС‹Рј РёРґРµРЅС‚РёС„РёРєР°С‚РѕСЂРѕРј
     * 				РїСЂРёР»РѕР¶РµРЅРёСЏ (uidApplication)
     */
    @WebMethod(action = "http://creditregistry.ru/2010/webservice/SingleFormatService/joinApplicationResponses")
    @Action(input = "http://creditregistry.ru/2010/webservice/SingleFormatService/joinApplicationResponses", output = "http://creditregistry.ru/2010/webservice/SingleFormatService/joinApplicationResponsesResponse")
    @WebResult(name = "ProcessRequestOut", targetNamespace = "http://creditregistry.ru/2010/webservice/SingleFormatService", partName = "joinedReport")
    public ProcessRequestOut joinApplicationResponses(
        @WebParam(partName = "authData", name = "AuthData", targetNamespace = "http://creditregistry.ru/2010/webservice/SingleFormatService")
        AuthData authData,
        @WebParam(partName = "requestData", name = "JoinApplicationResponsesData", targetNamespace = "http://creditregistry.ru/2010/webservice/SingleFormatService")
        JoinApplicationResponsesData requestData
    );

    @WebMethod(action = "http://creditregistry.ru/2010/webservice/SingleFormatService/joinApplicationResponsesWSI")
    @Action(input = "http://creditregistry.ru/2010/webservice/SingleFormatService/joinApplicationResponsesWSI", output = "http://creditregistry.ru/2010/webservice/SingleFormatService/joinApplicationResponsesWSIResponse")
    @WebResult(name = "ProcessRequestOut", targetNamespace = "http://creditregistry.ru/2010/webservice/SingleFormatService", partName = "joinedReport")
    public ProcessRequestOut joinApplicationResponsesWSI(
        @WebParam(partName = "requestData", name = "JoinApplicationResponsesData", targetNamespace = "http://creditregistry.ru/2010/webservice/SingleFormatService")
        JoinApplicationResponsesData requestData
    );

    @WebMethod(action = "http://creditregistry.ru/2010/webservice/SingleFormatService/processRequestWSI")
    @Action(input = "http://creditregistry.ru/2010/webservice/SingleFormatService/processRequestWSI", output = "http://creditregistry.ru/2010/webservice/SingleFormatService/processRequestWSIResponse")
    @WebResult(name = "ProcessRequestOut", targetNamespace = "http://creditregistry.ru/2010/webservice/SingleFormatService", partName = "report")
    public ProcessRequestOut processRequestWSI(
        @WebParam(partName = "requestData", name = "ProcessRequestData", targetNamespace = "http://creditregistry.ru/2010/webservice/SingleFormatService")
        ProcessRequestData requestData
    );

    /**
     * РњРµС‚РѕРґ РѕСЃСѓС‰РµСЃС‚РІР»СЏРµС‚ Р·Р°РїСЂРѕСЃ Рє РЅРµСЃРєРѕР»СЊРєРёРј Р‘РљР?,
     * 				РїСЂРѕРёР·РІРѕРґРёС‚ СѓРЅРёС„РёРєР°С†РёСЋ Рё СЃРІРµРґРµРЅРёРµ Рё
     * 				РІС‹РґР°РµС‚ РѕС‚РІРµС‚ РІ Р•РґРёРЅРѕРј С„РѕСЂРјР°С‚Рµ
     */
    @WebMethod(action = "http://creditregistry.ru/2010/webservice/SingleFormatService/groupRequest")
    @Action(input = "http://creditregistry.ru/2010/webservice/SingleFormatService/groupRequest", output = "http://creditregistry.ru/2010/webservice/SingleFormatService/groupRequestResponse")
    @WebResult(name = "ProcessRequestOut", targetNamespace = "http://creditregistry.ru/2010/webservice/SingleFormatService", partName = "joinedReport")
    public ProcessRequestOut groupRequest(
        @WebParam(partName = "authData", name = "AuthData", targetNamespace = "http://creditregistry.ru/2010/webservice/SingleFormatService")
        AuthData authData,
        @WebParam(partName = "requestData", name = "GroupRequestData", targetNamespace = "http://creditregistry.ru/2010/webservice/SingleFormatService")
        GroupRequestData requestData
    );

    @WebMethod(action = "http://creditregistry.ru/2010/webservice/SingleFormatService/statusUpdateWSI")
    @Action(input = "http://creditregistry.ru/2010/webservice/SingleFormatService/statusUpdateWSI", output = "http://creditregistry.ru/2010/webservice/SingleFormatService/statusUpdateWSIResponse")
    @WebResult(name = "ProcessRequestOut", targetNamespace = "http://creditregistry.ru/2010/webservice/SingleFormatService", partName = "joinedReport")
    public ProcessRequestOut statusUpdateWSI(
        @WebParam(partName = "requestData", name = "StatusUpdateData", targetNamespace = "http://creditregistry.ru/2010/webservice/SingleFormatService")
        StatusUpdateData requestData
    );

    /**
     * РњРµС‚РѕРґ РѕСЃСѓС‰РµСЃС‚РІР»СЏРµС‚ СЃРІРµРґРµРЅРёРµ РЅРµСЃРєРѕР»СЊРєРёС…
     * 				РѕС‚С‡С‘С‚РѕРІ, СѓРєР°Р·Р°РЅРЅС‹С… СЃ РїРѕРјРѕС‰СЊСЋ UID
     */
    @WebMethod(action = "http://creditregistry.ru/2010/webservice/SingleFormatService/joinUidResponses")
    @Action(input = "http://creditregistry.ru/2010/webservice/SingleFormatService/joinUidResponses", output = "http://creditregistry.ru/2010/webservice/SingleFormatService/joinUidResponsesResponse")
    @WebResult(name = "ProcessRequestOut", targetNamespace = "http://creditregistry.ru/2010/webservice/SingleFormatService", partName = "joinedReport")
    public ProcessRequestOut joinUidResponses(
        @WebParam(partName = "authData", name = "AuthData", targetNamespace = "http://creditregistry.ru/2010/webservice/SingleFormatService")
        AuthData authData,
        @WebParam(partName = "requestData", name = "JoinUidResponsesData", targetNamespace = "http://creditregistry.ru/2010/webservice/SingleFormatService")
        JoinUidResponsesData requestData
    );

    @WebMethod(action = "http://creditregistry.ru/2010/webservice/SingleFormatService/joinUidResponsesWSI")
    @Action(input = "http://creditregistry.ru/2010/webservice/SingleFormatService/joinUidResponsesWSI", output = "http://creditregistry.ru/2010/webservice/SingleFormatService/joinUidResponsesWSIResponse")
    @WebResult(name = "ProcessRequestOut", targetNamespace = "http://creditregistry.ru/2010/webservice/SingleFormatService", partName = "joinedReport")
    public ProcessRequestOut joinUidResponsesWSI(
        @WebParam(partName = "requestData", name = "JoinUidResponsesData", targetNamespace = "http://creditregistry.ru/2010/webservice/SingleFormatService")
        JoinUidResponsesData requestData
    );
}
