//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-27 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.03.04 at 11:42:46 AM MSK 
//


package ru.creditregistry._2010.webservice.singleformat.response;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for bankGuaranteeType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="bankGuaranteeType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="BANK_NAME" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CREDITOR_TYPE" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="IS_OWN" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="PURPOSE" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="AMOUNT_COVERED" type="{}moneyValueType" minOccurs="0"/>
 *         &lt;element name="AMOUNT_COVERED_CURRENCY" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AMOUNT" type="{}moneyValueType" minOccurs="0"/>
 *         &lt;element name="AMOUNT_CURRENCY" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="START_DATE" type="{}dateType" minOccurs="0"/>
 *         &lt;element name="FINISHED_DATE" type="{}dateType" minOccurs="0"/>
 *         &lt;element name="PLANNED_FINISHED_DATE" type="{}dateType" minOccurs="0"/>
 *         &lt;element name="CLOSURE_INFORMATION" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="COVERAGE_FLAG" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="INFO_SOURCES" type="{}infoSourcesType"/>
 *         &lt;element name="EXTENSION" type="{}extensionType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "bankGuaranteeType", propOrder = {
    "id",
    "bankname",
    "creditortype",
    "isown",
    "purpose",
    "amountcovered",
    "amountcoveredcurrency",
    "amount",
    "amountcurrency",
    "startdate",
    "finisheddate",
    "plannedfinisheddate",
    "closureinformation",
    "coverageflag",
    "infosources",
    "extension"
})
@XmlSeeAlso({
    PrincipalType.class
})
public class BankGuaranteeType {

    @XmlElement(name = "ID")
    protected String id;
    @XmlElement(name = "BANK_NAME")
    protected String bankname;
    @XmlElement(name = "CREDITOR_TYPE")
    protected Integer creditortype;
    @XmlElement(name = "IS_OWN")
    protected Integer isown;
    @XmlElement(name = "PURPOSE")
    protected Integer purpose;
    @XmlElement(name = "AMOUNT_COVERED")
    protected BigDecimal amountcovered;
    @XmlElement(name = "AMOUNT_COVERED_CURRENCY")
    protected String amountcoveredcurrency;
    @XmlElement(name = "AMOUNT")
    protected BigDecimal amount;
    @XmlElement(name = "AMOUNT_CURRENCY")
    protected String amountcurrency;
    @XmlElement(name = "START_DATE")
    protected String startdate;
    @XmlElement(name = "FINISHED_DATE")
    protected String finisheddate;
    @XmlElement(name = "PLANNED_FINISHED_DATE")
    protected String plannedfinisheddate;
    @XmlElement(name = "CLOSURE_INFORMATION")
    protected String closureinformation;
    @XmlElement(name = "COVERAGE_FLAG")
    protected Integer coverageflag;
    @XmlElement(name = "INFO_SOURCES", required = true)
    protected InfoSourcesType infosources;
    @XmlElement(name = "EXTENSION")
    protected ExtensionType extension;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setID(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the bankname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBANKNAME() {
        return bankname;
    }

    /**
     * Sets the value of the bankname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBANKNAME(String value) {
        this.bankname = value;
    }

    /**
     * Gets the value of the creditortype property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCREDITORTYPE() {
        return creditortype;
    }

    /**
     * Sets the value of the creditortype property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCREDITORTYPE(Integer value) {
        this.creditortype = value;
    }

    /**
     * Gets the value of the isown property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getISOWN() {
        return isown;
    }

    /**
     * Sets the value of the isown property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setISOWN(Integer value) {
        this.isown = value;
    }

    /**
     * Gets the value of the purpose property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getPURPOSE() {
        return purpose;
    }

    /**
     * Sets the value of the purpose property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setPURPOSE(Integer value) {
        this.purpose = value;
    }

    /**
     * Gets the value of the amountcovered property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getAMOUNTCOVERED() {
        return amountcovered;
    }

    /**
     * Sets the value of the amountcovered property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setAMOUNTCOVERED(BigDecimal value) {
        this.amountcovered = value;
    }

    /**
     * Gets the value of the amountcoveredcurrency property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAMOUNTCOVEREDCURRENCY() {
        return amountcoveredcurrency;
    }

    /**
     * Sets the value of the amountcoveredcurrency property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAMOUNTCOVEREDCURRENCY(String value) {
        this.amountcoveredcurrency = value;
    }

    /**
     * Gets the value of the amount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getAMOUNT() {
        return amount;
    }

    /**
     * Sets the value of the amount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setAMOUNT(BigDecimal value) {
        this.amount = value;
    }

    /**
     * Gets the value of the amountcurrency property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAMOUNTCURRENCY() {
        return amountcurrency;
    }

    /**
     * Sets the value of the amountcurrency property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAMOUNTCURRENCY(String value) {
        this.amountcurrency = value;
    }

    /**
     * Gets the value of the startdate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSTARTDATE() {
        return startdate;
    }

    /**
     * Sets the value of the startdate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSTARTDATE(String value) {
        this.startdate = value;
    }

    /**
     * Gets the value of the finisheddate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFINISHEDDATE() {
        return finisheddate;
    }

    /**
     * Sets the value of the finisheddate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFINISHEDDATE(String value) {
        this.finisheddate = value;
    }

    /**
     * Gets the value of the plannedfinisheddate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPLANNEDFINISHEDDATE() {
        return plannedfinisheddate;
    }

    /**
     * Sets the value of the plannedfinisheddate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPLANNEDFINISHEDDATE(String value) {
        this.plannedfinisheddate = value;
    }

    /**
     * Gets the value of the closureinformation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCLOSUREINFORMATION() {
        return closureinformation;
    }

    /**
     * Sets the value of the closureinformation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCLOSUREINFORMATION(String value) {
        this.closureinformation = value;
    }

    /**
     * Gets the value of the coverageflag property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCOVERAGEFLAG() {
        return coverageflag;
    }

    /**
     * Sets the value of the coverageflag property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCOVERAGEFLAG(Integer value) {
        this.coverageflag = value;
    }

    /**
     * Gets the value of the infosources property.
     * 
     * @return
     *     possible object is
     *     {@link InfoSourcesType }
     *     
     */
    public InfoSourcesType getINFOSOURCES() {
        return infosources;
    }

    /**
     * Sets the value of the infosources property.
     * 
     * @param value
     *     allowed object is
     *     {@link InfoSourcesType }
     *     
     */
    public void setINFOSOURCES(InfoSourcesType value) {
        this.infosources = value;
    }

    /**
     * Gets the value of the extension property.
     * 
     * @return
     *     possible object is
     *     {@link ExtensionType }
     *     
     */
    public ExtensionType getEXTENSION() {
        return extension;
    }

    /**
     * Sets the value of the extension property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExtensionType }
     *     
     */
    public void setEXTENSION(ExtensionType value) {
        this.extension = value;
    }

}
