//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-27 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.03.04 at 11:42:46 AM MSK 
//


package ru.creditregistry._2010.webservice.singleformat.response;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for pfrRecordType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="pfrRecordType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DOCUMENT_TYPE" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="DOCUMENT_SUBTYPE" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="SNILS" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="LAST_NAME" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="FIRST_NAME" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="SECOND_NAME" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="BIRTH_DATE" type="{}dateType" minOccurs="0"/>
 *         &lt;element name="RETURN_CODE" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="RETURN_TITLE" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="RETURN_DESCRIPTION" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="RETURN_DATETIME" type="{}dateTimeType" minOccurs="0"/>
 *         &lt;element name="LAST_UPDATE" type="{}dateType" minOccurs="0"/>
 *         &lt;element name="INCOME_YEAR" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="INCOME" type="{}moneyValueType" minOccurs="0"/>
 *         &lt;element name="INVEST_YEAR" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="INVEST_RATE" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="YEAR" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="ACCUMULATIVE" type="{}moneyValueType" minOccurs="0"/>
 *         &lt;element name="INVEST_INCOME" type="{}moneyValueType" minOccurs="0"/>
 *         &lt;element name="AMC_NAME" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="NPF_NAME" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PORTFOLIO_NAME" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AMC_ACC_AMOUNT" type="{}moneyValueType" minOccurs="0"/>
 *         &lt;element name="NPF_ACC_AMOUNT" type="{}moneyValueType" minOccurs="0"/>
 *         &lt;element name="CONTRIBUTIONS" type="{}contributionsType" minOccurs="0"/>
 *         &lt;element name="FIXED_PAYMENTS" type="{}fixedPaymentsType" minOccurs="0"/>
 *         &lt;element name="INS_CONTRIBUTIONS" type="{}insContributionsType" minOccurs="0"/>
 *         &lt;element name="COFIN_CONTRIBUTIONS" type="{}cofinContributionsType" minOccurs="0"/>
 *         &lt;element name="GENERAL_SUMS" type="{}generalSumsType" minOccurs="0"/>
 *         &lt;element name="GENERAL_PARTS" type="{}generalPartsType" minOccurs="0"/>
 *         &lt;element name="SPECIAL_PARTS" type="{}specialPartsType" minOccurs="0"/>
 *         &lt;element name="INFORMINGS" type="{}informingsType" minOccurs="0"/>
 *         &lt;element name="EXTENSION" type="{}extensionType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "pfrRecordType", propOrder = {
    "documenttype",
    "documentsubtype",
    "snils",
    "lastname",
    "firstname",
    "secondname",
    "birthdate",
    "returncode",
    "returntitle",
    "returndescription",
    "returndatetime",
    "lastupdate",
    "incomeyear",
    "income",
    "investyear",
    "investrate",
    "year",
    "accumulative",
    "investincome",
    "amcname",
    "npfname",
    "portfolioname",
    "amcaccamount",
    "npfaccamount",
    "contributions",
    "fixedpayments",
    "inscontributions",
    "cofincontributions",
    "generalsums",
    "generalparts",
    "specialparts",
    "informings",
    "extension"
})
public class PfrRecordType {

    @XmlElement(name = "DOCUMENT_TYPE", required = true)
    protected String documenttype;
    @XmlElement(name = "DOCUMENT_SUBTYPE")
    protected String documentsubtype;
    @XmlElement(name = "SNILS")
    protected String snils;
    @XmlElement(name = "LAST_NAME")
    protected String lastname;
    @XmlElement(name = "FIRST_NAME")
    protected String firstname;
    @XmlElement(name = "SECOND_NAME")
    protected String secondname;
    @XmlElement(name = "BIRTH_DATE")
    protected String birthdate;
    @XmlElement(name = "RETURN_CODE")
    protected Integer returncode;
    @XmlElement(name = "RETURN_TITLE")
    protected String returntitle;
    @XmlElement(name = "RETURN_DESCRIPTION")
    protected String returndescription;
    @XmlElement(name = "RETURN_DATETIME")
    protected String returndatetime;
    @XmlElement(name = "LAST_UPDATE")
    protected String lastupdate;
    @XmlElement(name = "INCOME_YEAR")
    protected Integer incomeyear;
    @XmlElement(name = "INCOME")
    protected BigDecimal income;
    @XmlElement(name = "INVEST_YEAR")
    protected Integer investyear;
    @XmlElement(name = "INVEST_RATE")
    protected BigDecimal investrate;
    @XmlElement(name = "YEAR")
    protected Integer year;
    @XmlElement(name = "ACCUMULATIVE")
    protected BigDecimal accumulative;
    @XmlElement(name = "INVEST_INCOME")
    protected BigDecimal investincome;
    @XmlElement(name = "AMC_NAME")
    protected String amcname;
    @XmlElement(name = "NPF_NAME")
    protected String npfname;
    @XmlElement(name = "PORTFOLIO_NAME")
    protected String portfolioname;
    @XmlElement(name = "AMC_ACC_AMOUNT")
    protected BigDecimal amcaccamount;
    @XmlElement(name = "NPF_ACC_AMOUNT")
    protected BigDecimal npfaccamount;
    @XmlElement(name = "CONTRIBUTIONS")
    protected ContributionsType contributions;
    @XmlElement(name = "FIXED_PAYMENTS")
    protected FixedPaymentsType fixedpayments;
    @XmlElement(name = "INS_CONTRIBUTIONS")
    protected InsContributionsType inscontributions;
    @XmlElement(name = "COFIN_CONTRIBUTIONS")
    protected CofinContributionsType cofincontributions;
    @XmlElement(name = "GENERAL_SUMS")
    protected GeneralSumsType generalsums;
    @XmlElement(name = "GENERAL_PARTS")
    protected GeneralPartsType generalparts;
    @XmlElement(name = "SPECIAL_PARTS")
    protected SpecialPartsType specialparts;
    @XmlElement(name = "INFORMINGS")
    protected InformingsType informings;
    @XmlElement(name = "EXTENSION")
    protected ExtensionType extension;

    /**
     * Gets the value of the documenttype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDOCUMENTTYPE() {
        return documenttype;
    }

    /**
     * Sets the value of the documenttype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDOCUMENTTYPE(String value) {
        this.documenttype = value;
    }

    /**
     * Gets the value of the documentsubtype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDOCUMENTSUBTYPE() {
        return documentsubtype;
    }

    /**
     * Sets the value of the documentsubtype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDOCUMENTSUBTYPE(String value) {
        this.documentsubtype = value;
    }

    /**
     * Gets the value of the snils property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSNILS() {
        return snils;
    }

    /**
     * Sets the value of the snils property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSNILS(String value) {
        this.snils = value;
    }

    /**
     * Gets the value of the lastname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLASTNAME() {
        return lastname;
    }

    /**
     * Sets the value of the lastname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLASTNAME(String value) {
        this.lastname = value;
    }

    /**
     * Gets the value of the firstname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFIRSTNAME() {
        return firstname;
    }

    /**
     * Sets the value of the firstname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFIRSTNAME(String value) {
        this.firstname = value;
    }

    /**
     * Gets the value of the secondname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSECONDNAME() {
        return secondname;
    }

    /**
     * Sets the value of the secondname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSECONDNAME(String value) {
        this.secondname = value;
    }

    /**
     * Gets the value of the birthdate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBIRTHDATE() {
        return birthdate;
    }

    /**
     * Sets the value of the birthdate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBIRTHDATE(String value) {
        this.birthdate = value;
    }

    /**
     * Gets the value of the returncode property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getRETURNCODE() {
        return returncode;
    }

    /**
     * Sets the value of the returncode property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setRETURNCODE(Integer value) {
        this.returncode = value;
    }

    /**
     * Gets the value of the returntitle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRETURNTITLE() {
        return returntitle;
    }

    /**
     * Sets the value of the returntitle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRETURNTITLE(String value) {
        this.returntitle = value;
    }

    /**
     * Gets the value of the returndescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRETURNDESCRIPTION() {
        return returndescription;
    }

    /**
     * Sets the value of the returndescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRETURNDESCRIPTION(String value) {
        this.returndescription = value;
    }

    /**
     * Gets the value of the returndatetime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRETURNDATETIME() {
        return returndatetime;
    }

    /**
     * Sets the value of the returndatetime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRETURNDATETIME(String value) {
        this.returndatetime = value;
    }

    /**
     * Gets the value of the lastupdate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLASTUPDATE() {
        return lastupdate;
    }

    /**
     * Sets the value of the lastupdate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLASTUPDATE(String value) {
        this.lastupdate = value;
    }

    /**
     * Gets the value of the incomeyear property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getINCOMEYEAR() {
        return incomeyear;
    }

    /**
     * Sets the value of the incomeyear property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setINCOMEYEAR(Integer value) {
        this.incomeyear = value;
    }

    /**
     * Gets the value of the income property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getINCOME() {
        return income;
    }

    /**
     * Sets the value of the income property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setINCOME(BigDecimal value) {
        this.income = value;
    }

    /**
     * Gets the value of the investyear property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getINVESTYEAR() {
        return investyear;
    }

    /**
     * Sets the value of the investyear property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setINVESTYEAR(Integer value) {
        this.investyear = value;
    }

    /**
     * Gets the value of the investrate property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getINVESTRATE() {
        return investrate;
    }

    /**
     * Sets the value of the investrate property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setINVESTRATE(BigDecimal value) {
        this.investrate = value;
    }

    /**
     * Gets the value of the year property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getYEAR() {
        return year;
    }

    /**
     * Sets the value of the year property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setYEAR(Integer value) {
        this.year = value;
    }

    /**
     * Gets the value of the accumulative property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getACCUMULATIVE() {
        return accumulative;
    }

    /**
     * Sets the value of the accumulative property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setACCUMULATIVE(BigDecimal value) {
        this.accumulative = value;
    }

    /**
     * Gets the value of the investincome property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getINVESTINCOME() {
        return investincome;
    }

    /**
     * Sets the value of the investincome property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setINVESTINCOME(BigDecimal value) {
        this.investincome = value;
    }

    /**
     * Gets the value of the amcname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAMCNAME() {
        return amcname;
    }

    /**
     * Sets the value of the amcname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAMCNAME(String value) {
        this.amcname = value;
    }

    /**
     * Gets the value of the npfname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNPFNAME() {
        return npfname;
    }

    /**
     * Sets the value of the npfname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNPFNAME(String value) {
        this.npfname = value;
    }

    /**
     * Gets the value of the portfolioname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPORTFOLIONAME() {
        return portfolioname;
    }

    /**
     * Sets the value of the portfolioname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPORTFOLIONAME(String value) {
        this.portfolioname = value;
    }

    /**
     * Gets the value of the amcaccamount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getAMCACCAMOUNT() {
        return amcaccamount;
    }

    /**
     * Sets the value of the amcaccamount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setAMCACCAMOUNT(BigDecimal value) {
        this.amcaccamount = value;
    }

    /**
     * Gets the value of the npfaccamount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getNPFACCAMOUNT() {
        return npfaccamount;
    }

    /**
     * Sets the value of the npfaccamount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setNPFACCAMOUNT(BigDecimal value) {
        this.npfaccamount = value;
    }

    /**
     * Gets the value of the contributions property.
     * 
     * @return
     *     possible object is
     *     {@link ContributionsType }
     *     
     */
    public ContributionsType getCONTRIBUTIONS() {
        return contributions;
    }

    /**
     * Sets the value of the contributions property.
     * 
     * @param value
     *     allowed object is
     *     {@link ContributionsType }
     *     
     */
    public void setCONTRIBUTIONS(ContributionsType value) {
        this.contributions = value;
    }

    /**
     * Gets the value of the fixedpayments property.
     * 
     * @return
     *     possible object is
     *     {@link FixedPaymentsType }
     *     
     */
    public FixedPaymentsType getFIXEDPAYMENTS() {
        return fixedpayments;
    }

    /**
     * Sets the value of the fixedpayments property.
     * 
     * @param value
     *     allowed object is
     *     {@link FixedPaymentsType }
     *     
     */
    public void setFIXEDPAYMENTS(FixedPaymentsType value) {
        this.fixedpayments = value;
    }

    /**
     * Gets the value of the inscontributions property.
     * 
     * @return
     *     possible object is
     *     {@link InsContributionsType }
     *     
     */
    public InsContributionsType getINSCONTRIBUTIONS() {
        return inscontributions;
    }

    /**
     * Sets the value of the inscontributions property.
     * 
     * @param value
     *     allowed object is
     *     {@link InsContributionsType }
     *     
     */
    public void setINSCONTRIBUTIONS(InsContributionsType value) {
        this.inscontributions = value;
    }

    /**
     * Gets the value of the cofincontributions property.
     * 
     * @return
     *     possible object is
     *     {@link CofinContributionsType }
     *     
     */
    public CofinContributionsType getCOFINCONTRIBUTIONS() {
        return cofincontributions;
    }

    /**
     * Sets the value of the cofincontributions property.
     * 
     * @param value
     *     allowed object is
     *     {@link CofinContributionsType }
     *     
     */
    public void setCOFINCONTRIBUTIONS(CofinContributionsType value) {
        this.cofincontributions = value;
    }

    /**
     * Gets the value of the generalsums property.
     * 
     * @return
     *     possible object is
     *     {@link GeneralSumsType }
     *     
     */
    public GeneralSumsType getGENERALSUMS() {
        return generalsums;
    }

    /**
     * Sets the value of the generalsums property.
     * 
     * @param value
     *     allowed object is
     *     {@link GeneralSumsType }
     *     
     */
    public void setGENERALSUMS(GeneralSumsType value) {
        this.generalsums = value;
    }

    /**
     * Gets the value of the generalparts property.
     * 
     * @return
     *     possible object is
     *     {@link GeneralPartsType }
     *     
     */
    public GeneralPartsType getGENERALPARTS() {
        return generalparts;
    }

    /**
     * Sets the value of the generalparts property.
     * 
     * @param value
     *     allowed object is
     *     {@link GeneralPartsType }
     *     
     */
    public void setGENERALPARTS(GeneralPartsType value) {
        this.generalparts = value;
    }

    /**
     * Gets the value of the specialparts property.
     * 
     * @return
     *     possible object is
     *     {@link SpecialPartsType }
     *     
     */
    public SpecialPartsType getSPECIALPARTS() {
        return specialparts;
    }

    /**
     * Sets the value of the specialparts property.
     * 
     * @param value
     *     allowed object is
     *     {@link SpecialPartsType }
     *     
     */
    public void setSPECIALPARTS(SpecialPartsType value) {
        this.specialparts = value;
    }

    /**
     * Gets the value of the informings property.
     * 
     * @return
     *     possible object is
     *     {@link InformingsType }
     *     
     */
    public InformingsType getINFORMINGS() {
        return informings;
    }

    /**
     * Sets the value of the informings property.
     * 
     * @param value
     *     allowed object is
     *     {@link InformingsType }
     *     
     */
    public void setINFORMINGS(InformingsType value) {
        this.informings = value;
    }

    /**
     * Gets the value of the extension property.
     * 
     * @return
     *     possible object is
     *     {@link ExtensionType }
     *     
     */
    public ExtensionType getEXTENSION() {
        return extension;
    }

    /**
     * Sets the value of the extension property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExtensionType }
     *     
     */
    public void setEXTENSION(ExtensionType value) {
        this.extension = value;
    }

}
