//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-27 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.03.04 at 11:42:46 AM MSK 
//


package ru.creditregistry._2010.webservice.singleformat.response;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for principalType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="principalType">
 *   &lt;complexContent>
 *     &lt;extension base="{}bankGuaranteeType">
 *       &lt;sequence>
 *         &lt;element name="NUMBER_OF_HOLDERS" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="FIRST_UPDATE" type="{}dateTimeType" minOccurs="0"/>
 *         &lt;element name="LAST_UPDATE" type="{}dateTimeType" minOccurs="0"/>
 *         &lt;element name="REPORT_DATE" type="{}dateType" minOccurs="0"/>
 *         &lt;element name="DESCRIPTION" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "principalType", propOrder = {
    "numberofholders",
    "firstupdate",
    "lastupdate",
    "reportdate",
    "description"
})
public class PrincipalType
    extends BankGuaranteeType
{

    @XmlElement(name = "NUMBER_OF_HOLDERS")
    protected Integer numberofholders;
    @XmlElement(name = "FIRST_UPDATE")
    protected String firstupdate;
    @XmlElement(name = "LAST_UPDATE")
    protected String lastupdate;
    @XmlElement(name = "REPORT_DATE")
    protected String reportdate;
    @XmlElement(name = "DESCRIPTION")
    protected String description;

    /**
     * Gets the value of the numberofholders property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getNUMBEROFHOLDERS() {
        return numberofholders;
    }

    /**
     * Sets the value of the numberofholders property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setNUMBEROFHOLDERS(Integer value) {
        this.numberofholders = value;
    }

    /**
     * Gets the value of the firstupdate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFIRSTUPDATE() {
        return firstupdate;
    }

    /**
     * Sets the value of the firstupdate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFIRSTUPDATE(String value) {
        this.firstupdate = value;
    }

    /**
     * Gets the value of the lastupdate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLASTUPDATE() {
        return lastupdate;
    }

    /**
     * Sets the value of the lastupdate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLASTUPDATE(String value) {
        this.lastupdate = value;
    }

    /**
     * Gets the value of the reportdate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getREPORTDATE() {
        return reportdate;
    }

    /**
     * Sets the value of the reportdate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setREPORTDATE(String value) {
        this.reportdate = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDESCRIPTION() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDESCRIPTION(String value) {
        this.description = value;
    }

}
