//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-27 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.03.04 at 11:42:46 AM MSK 
//


package ru.creditregistry._2010.webservice.singleformat.response;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="MAIN" type="{}mainType"/>
 *         &lt;element name="SECONDARY" type="{}secondaryType"/>
 *         &lt;element name="GENERAL" type="{}generalType"/>
 *         &lt;element name="NAMES" type="{}namesType" minOccurs="0"/>
 *         &lt;element name="DOCUMENTS" type="{}documentsType" minOccurs="0"/>
 *         &lt;element name="ADDRESSES" type="{}addressesType" minOccurs="0"/>
 *         &lt;element name="PHONES" type="{}phonesType" minOccurs="0"/>
 *         &lt;element name="EMPLOYMENTS" type="{}employmentsType" minOccurs="0"/>
 *         &lt;element name="LOANS_OVERVIEW" type="{}loansOverviewType" minOccurs="0"/>
 *         &lt;element name="LOANS" type="{}loansType" minOccurs="0"/>
 *         &lt;element name="COMPANY_CHECKS" type="{}companyTypeChecksType" minOccurs="0"/>
 *         &lt;element name="PASSPORT_CHECKS" type="{}passportChecksType" minOccurs="0"/>
 *         &lt;element name="SCORES" type="{}scoresType" minOccurs="0"/>
 *         &lt;element name="INQUIRIES" type="{}inquiriesType" minOccurs="0"/>
 *         &lt;element name="LEGALS" type="{}legalsType" minOccurs="0"/>
 *         &lt;element name="FRAUDS" type="{}fraudsType" minOccurs="0"/>
 *         &lt;element name="BUSINESSES" type="{}businessesType" minOccurs="0"/>
 *         &lt;element name="BANKRUPTCIES" type="{}bankruptciesType" minOccurs="0"/>
 *         &lt;element name="OFFICIALS" type="{}officialsType" minOccurs="0"/>
 *         &lt;element name="PFR_RECORDS" type="{}pfrRecordsType" minOccurs="0"/>
 *         &lt;element name="INFOPARTS" type="{}infopartsType" minOccurs="0"/>
 *         &lt;element name="PRINCIPALS" type="{}principalsType" minOccurs="0"/>
 *         &lt;element name="DEBTS" type="{}debtsType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "main",
    "secondary",
    "general",
    "names",
    "documents",
    "addresses",
    "phones",
    "employments",
    "loansoverview",
    "loans",
    "companychecks",
    "passportchecks",
    "scores",
    "inquiries",
    "legals",
    "frauds",
    "businesses",
    "bankruptcies",
    "officials",
    "pfrrecords",
    "infoparts",
    "principals",
    "debts"
})
@XmlRootElement(name = "SINGLE_FORMAT")
public class SINGLEFORMAT {

    @XmlElement(name = "MAIN", required = true)
    protected MainType main;
    @XmlElement(name = "SECONDARY", required = true)
    protected SecondaryType secondary;
    @XmlElement(name = "GENERAL", required = true)
    protected GeneralType general;
    @XmlElement(name = "NAMES")
    protected NamesType names;
    @XmlElement(name = "DOCUMENTS")
    protected DocumentsType documents;
    @XmlElement(name = "ADDRESSES")
    protected AddressesType addresses;
    @XmlElement(name = "PHONES")
    protected PhonesType phones;
    @XmlElement(name = "EMPLOYMENTS")
    protected EmploymentsType employments;
    @XmlElement(name = "LOANS_OVERVIEW")
    protected LoansOverviewType loansoverview;
    @XmlElement(name = "LOANS")
    protected LoansType loans;
    @XmlElement(name = "COMPANY_CHECKS")
    protected CompanyTypeChecksType companychecks;
    @XmlElement(name = "PASSPORT_CHECKS")
    protected PassportChecksType passportchecks;
    @XmlElement(name = "SCORES")
    protected ScoresType scores;
    @XmlElement(name = "INQUIRIES")
    protected InquiriesType inquiries;
    @XmlElement(name = "LEGALS")
    protected LegalsType legals;
    @XmlElement(name = "FRAUDS")
    protected FraudsType frauds;
    @XmlElement(name = "BUSINESSES")
    protected BusinessesType businesses;
    @XmlElement(name = "BANKRUPTCIES")
    protected BankruptciesType bankruptcies;
    @XmlElement(name = "OFFICIALS")
    protected OfficialsType officials;
    @XmlElement(name = "PFR_RECORDS")
    protected PfrRecordsType pfrrecords;
    @XmlElement(name = "INFOPARTS")
    protected InfopartsType infoparts;
    @XmlElement(name = "PRINCIPALS")
    protected PrincipalsType principals;
    @XmlElement(name = "DEBTS")
    protected DebtsType debts;

    /**
     * Gets the value of the main property.
     * 
     * @return
     *     possible object is
     *     {@link MainType }
     *     
     */
    public MainType getMAIN() {
        return main;
    }

    /**
     * Sets the value of the main property.
     * 
     * @param value
     *     allowed object is
     *     {@link MainType }
     *     
     */
    public void setMAIN(MainType value) {
        this.main = value;
    }

    /**
     * Gets the value of the secondary property.
     * 
     * @return
     *     possible object is
     *     {@link SecondaryType }
     *     
     */
    public SecondaryType getSECONDARY() {
        return secondary;
    }

    /**
     * Sets the value of the secondary property.
     * 
     * @param value
     *     allowed object is
     *     {@link SecondaryType }
     *     
     */
    public void setSECONDARY(SecondaryType value) {
        this.secondary = value;
    }

    /**
     * Gets the value of the general property.
     * 
     * @return
     *     possible object is
     *     {@link GeneralType }
     *     
     */
    public GeneralType getGENERAL() {
        return general;
    }

    /**
     * Sets the value of the general property.
     * 
     * @param value
     *     allowed object is
     *     {@link GeneralType }
     *     
     */
    public void setGENERAL(GeneralType value) {
        this.general = value;
    }

    /**
     * Gets the value of the names property.
     * 
     * @return
     *     possible object is
     *     {@link NamesType }
     *     
     */
    public NamesType getNAMES() {
        return names;
    }

    /**
     * Sets the value of the names property.
     * 
     * @param value
     *     allowed object is
     *     {@link NamesType }
     *     
     */
    public void setNAMES(NamesType value) {
        this.names = value;
    }

    /**
     * Gets the value of the documents property.
     * 
     * @return
     *     possible object is
     *     {@link DocumentsType }
     *     
     */
    public DocumentsType getDOCUMENTS() {
        return documents;
    }

    /**
     * Sets the value of the documents property.
     * 
     * @param value
     *     allowed object is
     *     {@link DocumentsType }
     *     
     */
    public void setDOCUMENTS(DocumentsType value) {
        this.documents = value;
    }

    /**
     * Gets the value of the addresses property.
     * 
     * @return
     *     possible object is
     *     {@link AddressesType }
     *     
     */
    public AddressesType getADDRESSES() {
        return addresses;
    }

    /**
     * Sets the value of the addresses property.
     * 
     * @param value
     *     allowed object is
     *     {@link AddressesType }
     *     
     */
    public void setADDRESSES(AddressesType value) {
        this.addresses = value;
    }

    /**
     * Gets the value of the phones property.
     * 
     * @return
     *     possible object is
     *     {@link PhonesType }
     *     
     */
    public PhonesType getPHONES() {
        return phones;
    }

    /**
     * Sets the value of the phones property.
     * 
     * @param value
     *     allowed object is
     *     {@link PhonesType }
     *     
     */
    public void setPHONES(PhonesType value) {
        this.phones = value;
    }

    /**
     * Gets the value of the employments property.
     * 
     * @return
     *     possible object is
     *     {@link EmploymentsType }
     *     
     */
    public EmploymentsType getEMPLOYMENTS() {
        return employments;
    }

    /**
     * Sets the value of the employments property.
     * 
     * @param value
     *     allowed object is
     *     {@link EmploymentsType }
     *     
     */
    public void setEMPLOYMENTS(EmploymentsType value) {
        this.employments = value;
    }

    /**
     * Gets the value of the loansoverview property.
     * 
     * @return
     *     possible object is
     *     {@link LoansOverviewType }
     *     
     */
    public LoansOverviewType getLOANSOVERVIEW() {
        return loansoverview;
    }

    /**
     * Sets the value of the loansoverview property.
     * 
     * @param value
     *     allowed object is
     *     {@link LoansOverviewType }
     *     
     */
    public void setLOANSOVERVIEW(LoansOverviewType value) {
        this.loansoverview = value;
    }

    /**
     * Gets the value of the loans property.
     * 
     * @return
     *     possible object is
     *     {@link LoansType }
     *     
     */
    public LoansType getLOANS() {
        return loans;
    }

    /**
     * Sets the value of the loans property.
     * 
     * @param value
     *     allowed object is
     *     {@link LoansType }
     *     
     */
    public void setLOANS(LoansType value) {
        this.loans = value;
    }

    /**
     * Gets the value of the companychecks property.
     * 
     * @return
     *     possible object is
     *     {@link CompanyTypeChecksType }
     *     
     */
    public CompanyTypeChecksType getCOMPANYCHECKS() {
        return companychecks;
    }

    /**
     * Sets the value of the companychecks property.
     * 
     * @param value
     *     allowed object is
     *     {@link CompanyTypeChecksType }
     *     
     */
    public void setCOMPANYCHECKS(CompanyTypeChecksType value) {
        this.companychecks = value;
    }

    /**
     * Gets the value of the passportchecks property.
     * 
     * @return
     *     possible object is
     *     {@link PassportChecksType }
     *     
     */
    public PassportChecksType getPASSPORTCHECKS() {
        return passportchecks;
    }

    /**
     * Sets the value of the passportchecks property.
     * 
     * @param value
     *     allowed object is
     *     {@link PassportChecksType }
     *     
     */
    public void setPASSPORTCHECKS(PassportChecksType value) {
        this.passportchecks = value;
    }

    /**
     * Gets the value of the scores property.
     * 
     * @return
     *     possible object is
     *     {@link ScoresType }
     *     
     */
    public ScoresType getSCORES() {
        return scores;
    }

    /**
     * Sets the value of the scores property.
     * 
     * @param value
     *     allowed object is
     *     {@link ScoresType }
     *     
     */
    public void setSCORES(ScoresType value) {
        this.scores = value;
    }

    /**
     * Gets the value of the inquiries property.
     * 
     * @return
     *     possible object is
     *     {@link InquiriesType }
     *     
     */
    public InquiriesType getINQUIRIES() {
        return inquiries;
    }

    /**
     * Sets the value of the inquiries property.
     * 
     * @param value
     *     allowed object is
     *     {@link InquiriesType }
     *     
     */
    public void setINQUIRIES(InquiriesType value) {
        this.inquiries = value;
    }

    /**
     * Gets the value of the legals property.
     * 
     * @return
     *     possible object is
     *     {@link LegalsType }
     *     
     */
    public LegalsType getLEGALS() {
        return legals;
    }

    /**
     * Sets the value of the legals property.
     * 
     * @param value
     *     allowed object is
     *     {@link LegalsType }
     *     
     */
    public void setLEGALS(LegalsType value) {
        this.legals = value;
    }

    /**
     * Gets the value of the frauds property.
     * 
     * @return
     *     possible object is
     *     {@link FraudsType }
     *     
     */
    public FraudsType getFRAUDS() {
        return frauds;
    }

    /**
     * Sets the value of the frauds property.
     * 
     * @param value
     *     allowed object is
     *     {@link FraudsType }
     *     
     */
    public void setFRAUDS(FraudsType value) {
        this.frauds = value;
    }

    /**
     * Gets the value of the businesses property.
     * 
     * @return
     *     possible object is
     *     {@link BusinessesType }
     *     
     */
    public BusinessesType getBUSINESSES() {
        return businesses;
    }

    /**
     * Sets the value of the businesses property.
     * 
     * @param value
     *     allowed object is
     *     {@link BusinessesType }
     *     
     */
    public void setBUSINESSES(BusinessesType value) {
        this.businesses = value;
    }

    /**
     * Gets the value of the bankruptcies property.
     * 
     * @return
     *     possible object is
     *     {@link BankruptciesType }
     *     
     */
    public BankruptciesType getBANKRUPTCIES() {
        return bankruptcies;
    }

    /**
     * Sets the value of the bankruptcies property.
     * 
     * @param value
     *     allowed object is
     *     {@link BankruptciesType }
     *     
     */
    public void setBANKRUPTCIES(BankruptciesType value) {
        this.bankruptcies = value;
    }

    /**
     * Gets the value of the officials property.
     * 
     * @return
     *     possible object is
     *     {@link OfficialsType }
     *     
     */
    public OfficialsType getOFFICIALS() {
        return officials;
    }

    /**
     * Sets the value of the officials property.
     * 
     * @param value
     *     allowed object is
     *     {@link OfficialsType }
     *     
     */
    public void setOFFICIALS(OfficialsType value) {
        this.officials = value;
    }

    /**
     * Gets the value of the pfrrecords property.
     * 
     * @return
     *     possible object is
     *     {@link PfrRecordsType }
     *     
     */
    public PfrRecordsType getPFRRECORDS() {
        return pfrrecords;
    }

    /**
     * Sets the value of the pfrrecords property.
     * 
     * @param value
     *     allowed object is
     *     {@link PfrRecordsType }
     *     
     */
    public void setPFRRECORDS(PfrRecordsType value) {
        this.pfrrecords = value;
    }

    /**
     * Gets the value of the infoparts property.
     * 
     * @return
     *     possible object is
     *     {@link InfopartsType }
     *     
     */
    public InfopartsType getINFOPARTS() {
        return infoparts;
    }

    /**
     * Sets the value of the infoparts property.
     * 
     * @param value
     *     allowed object is
     *     {@link InfopartsType }
     *     
     */
    public void setINFOPARTS(InfopartsType value) {
        this.infoparts = value;
    }

    /**
     * Gets the value of the principals property.
     * 
     * @return
     *     possible object is
     *     {@link PrincipalsType }
     *     
     */
    public PrincipalsType getPRINCIPALS() {
        return principals;
    }

    /**
     * Sets the value of the principals property.
     * 
     * @param value
     *     allowed object is
     *     {@link PrincipalsType }
     *     
     */
    public void setPRINCIPALS(PrincipalsType value) {
        this.principals = value;
    }

    /**
     * Gets the value of the debts property.
     * 
     * @return
     *     possible object is
     *     {@link DebtsType }
     *     
     */
    public DebtsType getDEBTS() {
        return debts;
    }

    /**
     * Sets the value of the debts property.
     * 
     * @param value
     *     allowed object is
     *     {@link DebtsType }
     *     
     */
    public void setDEBTS(DebtsType value) {
        this.debts = value;
    }

}
