//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-27 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.03.04 at 11:42:46 AM MSK 
//


package ru.creditregistry._2010.webservice.singleformat.response;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Сводные данные об арбитражных делах
 * 
 * <p>Java class for sparkArbitrationSummary complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="sparkArbitrationSummary">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Plaintiff" type="{}sparkArbitrationSummaryByRole"/>
 *         &lt;element name="Defendant" type="{}sparkArbitrationSummaryByRole"/>
 *         &lt;element name="ArbitrationByType" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Type" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Plaintiff" type="{}sparkArbitrationSummaryByRoleShort"/>
 *                             &lt;element name="Defendant" type="{}sparkArbitrationSummaryByRoleShort"/>
 *                           &lt;/sequence>
 *                           &lt;attribute name="Id" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                           &lt;attribute name="Name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="ArbitrationByYear">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Year" type="{}sparkArbitrationSummaryByYear" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="Total" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="Considered" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="Appealed" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="DecisionsAndRulings" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="Completed" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "sparkArbitrationSummary", propOrder = {
    "plaintiff",
    "defendant",
    "arbitrationByType",
    "arbitrationByYear"
})
public class SparkArbitrationSummary {

    @XmlElement(name = "Plaintiff", required = true)
    protected SparkArbitrationSummaryByRole plaintiff;
    @XmlElement(name = "Defendant", required = true)
    protected SparkArbitrationSummaryByRole defendant;
    @XmlElement(name = "ArbitrationByType")
    protected SparkArbitrationSummary.ArbitrationByType arbitrationByType;
    @XmlElement(name = "ArbitrationByYear", required = true)
    protected SparkArbitrationSummary.ArbitrationByYear arbitrationByYear;
    @XmlAttribute(name = "Total", required = true)
    protected int total;
    @XmlAttribute(name = "Considered", required = true)
    protected int considered;
    @XmlAttribute(name = "Appealed", required = true)
    protected int appealed;
    @XmlAttribute(name = "DecisionsAndRulings", required = true)
    protected int decisionsAndRulings;
    @XmlAttribute(name = "Completed", required = true)
    protected int completed;

    /**
     * Gets the value of the plaintiff property.
     * 
     * @return
     *     possible object is
     *     {@link SparkArbitrationSummaryByRole }
     *     
     */
    public SparkArbitrationSummaryByRole getPlaintiff() {
        return plaintiff;
    }

    /**
     * Sets the value of the plaintiff property.
     * 
     * @param value
     *     allowed object is
     *     {@link SparkArbitrationSummaryByRole }
     *     
     */
    public void setPlaintiff(SparkArbitrationSummaryByRole value) {
        this.plaintiff = value;
    }

    /**
     * Gets the value of the defendant property.
     * 
     * @return
     *     possible object is
     *     {@link SparkArbitrationSummaryByRole }
     *     
     */
    public SparkArbitrationSummaryByRole getDefendant() {
        return defendant;
    }

    /**
     * Sets the value of the defendant property.
     * 
     * @param value
     *     allowed object is
     *     {@link SparkArbitrationSummaryByRole }
     *     
     */
    public void setDefendant(SparkArbitrationSummaryByRole value) {
        this.defendant = value;
    }

    /**
     * Gets the value of the arbitrationByType property.
     * 
     * @return
     *     possible object is
     *     {@link SparkArbitrationSummary.ArbitrationByType }
     *     
     */
    public SparkArbitrationSummary.ArbitrationByType getArbitrationByType() {
        return arbitrationByType;
    }

    /**
     * Sets the value of the arbitrationByType property.
     * 
     * @param value
     *     allowed object is
     *     {@link SparkArbitrationSummary.ArbitrationByType }
     *     
     */
    public void setArbitrationByType(SparkArbitrationSummary.ArbitrationByType value) {
        this.arbitrationByType = value;
    }

    /**
     * Gets the value of the arbitrationByYear property.
     * 
     * @return
     *     possible object is
     *     {@link SparkArbitrationSummary.ArbitrationByYear }
     *     
     */
    public SparkArbitrationSummary.ArbitrationByYear getArbitrationByYear() {
        return arbitrationByYear;
    }

    /**
     * Sets the value of the arbitrationByYear property.
     * 
     * @param value
     *     allowed object is
     *     {@link SparkArbitrationSummary.ArbitrationByYear }
     *     
     */
    public void setArbitrationByYear(SparkArbitrationSummary.ArbitrationByYear value) {
        this.arbitrationByYear = value;
    }

    /**
     * Gets the value of the total property.
     * 
     */
    public int getTotal() {
        return total;
    }

    /**
     * Sets the value of the total property.
     * 
     */
    public void setTotal(int value) {
        this.total = value;
    }

    /**
     * Gets the value of the considered property.
     * 
     */
    public int getConsidered() {
        return considered;
    }

    /**
     * Sets the value of the considered property.
     * 
     */
    public void setConsidered(int value) {
        this.considered = value;
    }

    /**
     * Gets the value of the appealed property.
     * 
     */
    public int getAppealed() {
        return appealed;
    }

    /**
     * Sets the value of the appealed property.
     * 
     */
    public void setAppealed(int value) {
        this.appealed = value;
    }

    /**
     * Gets the value of the decisionsAndRulings property.
     * 
     */
    public int getDecisionsAndRulings() {
        return decisionsAndRulings;
    }

    /**
     * Sets the value of the decisionsAndRulings property.
     * 
     */
    public void setDecisionsAndRulings(int value) {
        this.decisionsAndRulings = value;
    }

    /**
     * Gets the value of the completed property.
     * 
     */
    public int getCompleted() {
        return completed;
    }

    /**
     * Sets the value of the completed property.
     * 
     */
    public void setCompleted(int value) {
        this.completed = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Type" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Plaintiff" type="{}sparkArbitrationSummaryByRoleShort"/>
     *                   &lt;element name="Defendant" type="{}sparkArbitrationSummaryByRoleShort"/>
     *                 &lt;/sequence>
     *                 &lt;attribute name="Id" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
     *                 &lt;attribute name="Name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "type"
    })
    public static class ArbitrationByType {

        @XmlElement(name = "Type", required = true)
        protected List<SparkArbitrationSummary.ArbitrationByType.Type> type;

        /**
         * Gets the value of the type property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the type property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getType().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link SparkArbitrationSummary.ArbitrationByType.Type }
         * 
         * 
         */
        public List<SparkArbitrationSummary.ArbitrationByType.Type> getType() {
            if (type == null) {
                type = new ArrayList<SparkArbitrationSummary.ArbitrationByType.Type>();
            }
            return this.type;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Plaintiff" type="{}sparkArbitrationSummaryByRoleShort"/>
         *         &lt;element name="Defendant" type="{}sparkArbitrationSummaryByRoleShort"/>
         *       &lt;/sequence>
         *       &lt;attribute name="Id" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
         *       &lt;attribute name="Name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "plaintiff",
            "defendant"
        })
        public static class Type {

            @XmlElement(name = "Plaintiff", required = true)
            protected SparkArbitrationSummaryByRoleShort plaintiff;
            @XmlElement(name = "Defendant", required = true)
            protected SparkArbitrationSummaryByRoleShort defendant;
            @XmlAttribute(name = "Id", required = true)
            protected int id;
            @XmlAttribute(name = "Name", required = true)
            protected String name;

            /**
             * Gets the value of the plaintiff property.
             * 
             * @return
             *     possible object is
             *     {@link SparkArbitrationSummaryByRoleShort }
             *     
             */
            public SparkArbitrationSummaryByRoleShort getPlaintiff() {
                return plaintiff;
            }

            /**
             * Sets the value of the plaintiff property.
             * 
             * @param value
             *     allowed object is
             *     {@link SparkArbitrationSummaryByRoleShort }
             *     
             */
            public void setPlaintiff(SparkArbitrationSummaryByRoleShort value) {
                this.plaintiff = value;
            }

            /**
             * Gets the value of the defendant property.
             * 
             * @return
             *     possible object is
             *     {@link SparkArbitrationSummaryByRoleShort }
             *     
             */
            public SparkArbitrationSummaryByRoleShort getDefendant() {
                return defendant;
            }

            /**
             * Sets the value of the defendant property.
             * 
             * @param value
             *     allowed object is
             *     {@link SparkArbitrationSummaryByRoleShort }
             *     
             */
            public void setDefendant(SparkArbitrationSummaryByRoleShort value) {
                this.defendant = value;
            }

            /**
             * Gets the value of the id property.
             * 
             */
            public int getId() {
                return id;
            }

            /**
             * Sets the value of the id property.
             * 
             */
            public void setId(int value) {
                this.id = value;
            }

            /**
             * Gets the value of the name property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getName() {
                return name;
            }

            /**
             * Sets the value of the name property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setName(String value) {
                this.name = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Year" type="{}sparkArbitrationSummaryByYear" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "year"
    })
    public static class ArbitrationByYear {

        @XmlElement(name = "Year", required = true)
        protected List<SparkArbitrationSummaryByYear> year;

        /**
         * Gets the value of the year property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the year property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getYear().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link SparkArbitrationSummaryByYear }
         * 
         * 
         */
        public List<SparkArbitrationSummaryByYear> getYear() {
            if (year == null) {
                year = new ArrayList<SparkArbitrationSummaryByYear>();
            }
            return this.year;
        }

    }

}
