//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-27 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.03.04 at 11:42:46 AM MSK 
//


package ru.creditregistry._2010.webservice.singleformat.response;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * Компания
 * 
 * <p>Java class for sparkCompanyType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="sparkCompanyType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="SPARKID" type="{}sparkSparkID" minOccurs="0"/>
 *         &lt;element name="SparkID" type="{}sparkSparkID" minOccurs="0"/>
 *         &lt;element name="Address" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="INN" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="OGRN" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="OKPO" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="OKOPFName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Manager" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ManagerInn" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="FullName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="OKATO" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "sparkCompanyType", propOrder = {
    "name",
    "sparkid",
    "sparkID",
    "address",
    "inn",
    "ogrn",
    "okpo",
    "okopfName",
    "manager",
    "managerInn",
    "fullName",
    "okato"
})
@XmlSeeAlso({
    ru.creditregistry._2010.webservice.singleformat.response.SparkResponseType.Data.Report.AffiliatedCompaniesEGRUL.AffiliatedCompanyEGRUL.class,
    ru.creditregistry._2010.webservice.singleformat.response.SparkResponseType.Data.Report.AffiliatedCompaniesFCSM.AffiliatedCompanyFCSM.class,
    ru.creditregistry._2010.webservice.singleformat.response.SparkResponseType.Data.Report.AffiliatedCompaniesRosstat.AffiliatedCompanyRosstat.class,
    ru.creditregistry._2010.webservice.singleformat.response.SparkResponseType.Data.Report.CoownersEGRUL.CoownerEGRUL.class,
    ru.creditregistry._2010.webservice.singleformat.response.SparkResponseType.Data.Report.CoownersFCSM.CoownerFCSM.class,
    ru.creditregistry._2010.webservice.singleformat.response.SparkResponseType.Data.Report.CoownersRosstat.CoownerRosstat.class,
    ru.creditregistry._2010.webservice.singleformat.response.SparkResponseType.Data.Report.MainCoowners.Coowner.class
})
public class SparkCompanyType {

    @XmlElement(name = "Name", required = true)
    protected String name;
    @XmlElement(name = "SPARKID")
    protected Integer sparkid;
    @XmlElement(name = "SparkID")
    protected Integer sparkID;
    @XmlElement(name = "Address")
    protected String address;
    @XmlElement(name = "INN")
    protected String inn;
    @XmlElement(name = "OGRN")
    protected String ogrn;
    @XmlElement(name = "OKPO")
    protected String okpo;
    @XmlElement(name = "OKOPFName")
    protected String okopfName;
    @XmlElement(name = "Manager")
    protected String manager;
    @XmlElement(name = "ManagerInn")
    protected String managerInn;
    @XmlElement(name = "FullName")
    protected String fullName;
    @XmlElement(name = "OKATO")
    protected String okato;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the sparkid property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getSPARKID() {
        return sparkid;
    }

    /**
     * Sets the value of the sparkid property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setSPARKID(Integer value) {
        this.sparkid = value;
    }

    /**
     * Gets the value of the sparkID property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getSparkID() {
        return sparkID;
    }

    /**
     * Sets the value of the sparkID property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setSparkID(Integer value) {
        this.sparkID = value;
    }

    /**
     * Gets the value of the address property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddress() {
        return address;
    }

    /**
     * Sets the value of the address property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddress(String value) {
        this.address = value;
    }

    /**
     * Gets the value of the inn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getINN() {
        return inn;
    }

    /**
     * Sets the value of the inn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setINN(String value) {
        this.inn = value;
    }

    /**
     * Gets the value of the ogrn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOGRN() {
        return ogrn;
    }

    /**
     * Sets the value of the ogrn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOGRN(String value) {
        this.ogrn = value;
    }

    /**
     * Gets the value of the okpo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOKPO() {
        return okpo;
    }

    /**
     * Sets the value of the okpo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOKPO(String value) {
        this.okpo = value;
    }

    /**
     * Gets the value of the okopfName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOKOPFName() {
        return okopfName;
    }

    /**
     * Sets the value of the okopfName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOKOPFName(String value) {
        this.okopfName = value;
    }

    /**
     * Gets the value of the manager property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getManager() {
        return manager;
    }

    /**
     * Sets the value of the manager property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setManager(String value) {
        this.manager = value;
    }

    /**
     * Gets the value of the managerInn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getManagerInn() {
        return managerInn;
    }

    /**
     * Sets the value of the managerInn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setManagerInn(String value) {
        this.managerInn = value;
    }

    /**
     * Gets the value of the fullName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFullName() {
        return fullName;
    }

    /**
     * Sets the value of the fullName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFullName(String value) {
        this.fullName = value;
    }

    /**
     * Gets the value of the okato property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOKATO() {
        return okato;
    }

    /**
     * Sets the value of the okato property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOKATO(String value) {
        this.okato = value;
    }

}
