//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-27 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.03.04 at 11:42:46 AM MSK 
//


package ru.creditregistry._2010.webservice.singleformat.response;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;


/**
 * Сводные данные о договорах залога
 * 
 * <p>Java class for sparkPledgesSummary complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="sparkPledgesSummary">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded">
 *         &lt;element name="Pledger" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="Active" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                 &lt;attribute name="Ceased" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Pledgee" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="Active" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                 &lt;attribute name="Ceased" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Pledge" type="{}sparkPledgeByVIN" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "sparkPledgesSummary", propOrder = {
    "pledgerOrPledgeeOrPledge"
})
public class SparkPledgesSummary {

    @XmlElements({
        @XmlElement(name = "Pledger", type = SparkPledgesSummary.Pledger.class),
        @XmlElement(name = "Pledge", type = SparkPledgeByVIN.class),
        @XmlElement(name = "Pledgee", type = SparkPledgesSummary.Pledgee.class)
    })
    protected List<Object> pledgerOrPledgeeOrPledge;

    /**
     * Gets the value of the pledgerOrPledgeeOrPledge property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the pledgerOrPledgeeOrPledge property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPledgerOrPledgeeOrPledge().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SparkPledgesSummary.Pledger }
     * {@link SparkPledgeByVIN }
     * {@link SparkPledgesSummary.Pledgee }
     * 
     * 
     */
    public List<Object> getPledgerOrPledgeeOrPledge() {
        if (pledgerOrPledgeeOrPledge == null) {
            pledgerOrPledgeeOrPledge = new ArrayList<Object>();
        }
        return this.pledgerOrPledgeeOrPledge;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="Active" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
     *       &lt;attribute name="Ceased" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Pledgee {

        @XmlAttribute(name = "Active", required = true)
        protected int active;
        @XmlAttribute(name = "Ceased", required = true)
        protected int ceased;

        /**
         * Gets the value of the active property.
         * 
         */
        public int getActive() {
            return active;
        }

        /**
         * Sets the value of the active property.
         * 
         */
        public void setActive(int value) {
            this.active = value;
        }

        /**
         * Gets the value of the ceased property.
         * 
         */
        public int getCeased() {
            return ceased;
        }

        /**
         * Sets the value of the ceased property.
         * 
         */
        public void setCeased(int value) {
            this.ceased = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="Active" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
     *       &lt;attribute name="Ceased" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Pledger {

        @XmlAttribute(name = "Active", required = true)
        protected int active;
        @XmlAttribute(name = "Ceased", required = true)
        protected int ceased;

        /**
         * Gets the value of the active property.
         * 
         */
        public int getActive() {
            return active;
        }

        /**
         * Sets the value of the active property.
         * 
         */
        public void setActive(int value) {
            this.active = value;
        }

        /**
         * Gets the value of the ceased property.
         * 
         */
        public int getCeased() {
            return ceased;
        }

        /**
         * Sets the value of the ceased property.
         * 
         */
        public void setCeased(int value) {
            this.ceased = value;
        }

    }

}
