//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-27 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.03.04 at 11:42:46 AM MSK 
//


package ru.creditregistry._2010.webservice.singleformat.response;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * Сводные данные об арбитражных делах для отдельной роли участника
 * 
 * <p>Java class for sparkArbitrationSummaryByRole complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="sparkArbitrationSummaryByRole">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="Total" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="TotalSum" use="required" type="{}sparkMyDecimal" />
 *       &lt;attribute name="Considered" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="ConsideredSum" use="required" type="{}sparkMyDecimal" />
 *       &lt;attribute name="Appealed" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="AppealedSum" use="required" type="{}sparkMyDecimal" />
 *       &lt;attribute name="DecisionsAndRulings" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="DecisionsAndRulingsSum" use="required" type="{}sparkMyDecimal" />
 *       &lt;attribute name="Completed" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="CompletedSum" use="required" type="{}sparkMyDecimal" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "sparkArbitrationSummaryByRole")
public class SparkArbitrationSummaryByRole {

    @XmlAttribute(name = "Total", required = true)
    protected int total;
    @XmlAttribute(name = "TotalSum", required = true)
    protected String totalSum;
    @XmlAttribute(name = "Considered", required = true)
    protected int considered;
    @XmlAttribute(name = "ConsideredSum", required = true)
    protected String consideredSum;
    @XmlAttribute(name = "Appealed", required = true)
    protected int appealed;
    @XmlAttribute(name = "AppealedSum", required = true)
    protected String appealedSum;
    @XmlAttribute(name = "DecisionsAndRulings", required = true)
    protected int decisionsAndRulings;
    @XmlAttribute(name = "DecisionsAndRulingsSum", required = true)
    protected String decisionsAndRulingsSum;
    @XmlAttribute(name = "Completed", required = true)
    protected int completed;
    @XmlAttribute(name = "CompletedSum", required = true)
    protected String completedSum;

    /**
     * Gets the value of the total property.
     * 
     */
    public int getTotal() {
        return total;
    }

    /**
     * Sets the value of the total property.
     * 
     */
    public void setTotal(int value) {
        this.total = value;
    }

    /**
     * Gets the value of the totalSum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTotalSum() {
        return totalSum;
    }

    /**
     * Sets the value of the totalSum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTotalSum(String value) {
        this.totalSum = value;
    }

    /**
     * Gets the value of the considered property.
     * 
     */
    public int getConsidered() {
        return considered;
    }

    /**
     * Sets the value of the considered property.
     * 
     */
    public void setConsidered(int value) {
        this.considered = value;
    }

    /**
     * Gets the value of the consideredSum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConsideredSum() {
        return consideredSum;
    }

    /**
     * Sets the value of the consideredSum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConsideredSum(String value) {
        this.consideredSum = value;
    }

    /**
     * Gets the value of the appealed property.
     * 
     */
    public int getAppealed() {
        return appealed;
    }

    /**
     * Sets the value of the appealed property.
     * 
     */
    public void setAppealed(int value) {
        this.appealed = value;
    }

    /**
     * Gets the value of the appealedSum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAppealedSum() {
        return appealedSum;
    }

    /**
     * Sets the value of the appealedSum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAppealedSum(String value) {
        this.appealedSum = value;
    }

    /**
     * Gets the value of the decisionsAndRulings property.
     * 
     */
    public int getDecisionsAndRulings() {
        return decisionsAndRulings;
    }

    /**
     * Sets the value of the decisionsAndRulings property.
     * 
     */
    public void setDecisionsAndRulings(int value) {
        this.decisionsAndRulings = value;
    }

    /**
     * Gets the value of the decisionsAndRulingsSum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDecisionsAndRulingsSum() {
        return decisionsAndRulingsSum;
    }

    /**
     * Sets the value of the decisionsAndRulingsSum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDecisionsAndRulingsSum(String value) {
        this.decisionsAndRulingsSum = value;
    }

    /**
     * Gets the value of the completed property.
     * 
     */
    public int getCompleted() {
        return completed;
    }

    /**
     * Sets the value of the completed property.
     * 
     */
    public void setCompleted(int value) {
        this.completed = value;
    }

    /**
     * Gets the value of the completedSum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCompletedSum() {
        return completedSum;
    }

    /**
     * Sets the value of the completedSum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCompletedSum(String value) {
        this.completedSum = value;
    }

}
