//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-27 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.03.04 at 11:42:46 AM MSK 
//


package ru.creditregistry._2010.webservice.singleformat.response;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * Договор залога по VIN
 * 
 * <p>Java class for sparkPledgeByVIN complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="sparkPledgeByVIN">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="StopReason" minOccurs="0">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                 &lt;attribute name="Date" type="{http://www.w3.org/2001/XMLSchema}date" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Pledgers">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Participant" type="{}sparkPledgeParticipant" maxOccurs="unbounded" minOccurs="0"/>
 *                   &lt;element name="ParticipantId" type="{http://www.w3.org/2001/XMLSchema}int" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Pledgees">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Participant" type="{}sparkPledgeParticipant" maxOccurs="unbounded" minOccurs="0"/>
 *                   &lt;element name="ParticipantId" type="{http://www.w3.org/2001/XMLSchema}int" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="PledgedProperty">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;choice maxOccurs="unbounded">
 *                   &lt;element name="Item" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;simpleContent>
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                           &lt;attribute name="Type" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/extension>
 *                       &lt;/simpleContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="PropertyType" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/choice>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="Id" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="IsActing" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="NotificationNumber" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="ContractNumber" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="ContractDate" type="{http://www.w3.org/2001/XMLSchema}date" />
 *       &lt;attribute name="PerformanceDate" type="{http://www.w3.org/2001/XMLSchema}date" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "sparkPledgeByVIN", propOrder = {
    "stopReason",
    "pledgers",
    "pledgees",
    "pledgedProperty"
})
public class SparkPledgeByVIN {

    @XmlElement(name = "StopReason")
    protected SparkPledgeByVIN.StopReason stopReason;
    @XmlElement(name = "Pledgers", required = true)
    protected SparkPledgeByVIN.Pledgers pledgers;
    @XmlElement(name = "Pledgees", required = true)
    protected SparkPledgeByVIN.Pledgees pledgees;
    @XmlElement(name = "PledgedProperty", required = true)
    protected SparkPledgeByVIN.PledgedProperty pledgedProperty;
    @XmlAttribute(name = "Id", required = true)
    protected int id;
    @XmlAttribute(name = "IsActing", required = true)
    protected boolean isActing;
    @XmlAttribute(name = "NotificationNumber")
    protected String notificationNumber;
    @XmlAttribute(name = "ContractNumber")
    protected String contractNumber;
    @XmlAttribute(name = "ContractDate")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar contractDate;
    @XmlAttribute(name = "PerformanceDate")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar performanceDate;

    /**
     * Gets the value of the stopReason property.
     * 
     * @return
     *     possible object is
     *     {@link SparkPledgeByVIN.StopReason }
     *     
     */
    public SparkPledgeByVIN.StopReason getStopReason() {
        return stopReason;
    }

    /**
     * Sets the value of the stopReason property.
     * 
     * @param value
     *     allowed object is
     *     {@link SparkPledgeByVIN.StopReason }
     *     
     */
    public void setStopReason(SparkPledgeByVIN.StopReason value) {
        this.stopReason = value;
    }

    /**
     * Gets the value of the pledgers property.
     * 
     * @return
     *     possible object is
     *     {@link SparkPledgeByVIN.Pledgers }
     *     
     */
    public SparkPledgeByVIN.Pledgers getPledgers() {
        return pledgers;
    }

    /**
     * Sets the value of the pledgers property.
     * 
     * @param value
     *     allowed object is
     *     {@link SparkPledgeByVIN.Pledgers }
     *     
     */
    public void setPledgers(SparkPledgeByVIN.Pledgers value) {
        this.pledgers = value;
    }

    /**
     * Gets the value of the pledgees property.
     * 
     * @return
     *     possible object is
     *     {@link SparkPledgeByVIN.Pledgees }
     *     
     */
    public SparkPledgeByVIN.Pledgees getPledgees() {
        return pledgees;
    }

    /**
     * Sets the value of the pledgees property.
     * 
     * @param value
     *     allowed object is
     *     {@link SparkPledgeByVIN.Pledgees }
     *     
     */
    public void setPledgees(SparkPledgeByVIN.Pledgees value) {
        this.pledgees = value;
    }

    /**
     * Gets the value of the pledgedProperty property.
     * 
     * @return
     *     possible object is
     *     {@link SparkPledgeByVIN.PledgedProperty }
     *     
     */
    public SparkPledgeByVIN.PledgedProperty getPledgedProperty() {
        return pledgedProperty;
    }

    /**
     * Sets the value of the pledgedProperty property.
     * 
     * @param value
     *     allowed object is
     *     {@link SparkPledgeByVIN.PledgedProperty }
     *     
     */
    public void setPledgedProperty(SparkPledgeByVIN.PledgedProperty value) {
        this.pledgedProperty = value;
    }

    /**
     * Gets the value of the id property.
     * 
     */
    public int getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     */
    public void setId(int value) {
        this.id = value;
    }

    /**
     * Gets the value of the isActing property.
     * 
     */
    public boolean isIsActing() {
        return isActing;
    }

    /**
     * Sets the value of the isActing property.
     * 
     */
    public void setIsActing(boolean value) {
        this.isActing = value;
    }

    /**
     * Gets the value of the notificationNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNotificationNumber() {
        return notificationNumber;
    }

    /**
     * Sets the value of the notificationNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNotificationNumber(String value) {
        this.notificationNumber = value;
    }

    /**
     * Gets the value of the contractNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContractNumber() {
        return contractNumber;
    }

    /**
     * Sets the value of the contractNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContractNumber(String value) {
        this.contractNumber = value;
    }

    /**
     * Gets the value of the contractDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getContractDate() {
        return contractDate;
    }

    /**
     * Sets the value of the contractDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setContractDate(XMLGregorianCalendar value) {
        this.contractDate = value;
    }

    /**
     * Gets the value of the performanceDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getPerformanceDate() {
        return performanceDate;
    }

    /**
     * Sets the value of the performanceDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setPerformanceDate(XMLGregorianCalendar value) {
        this.performanceDate = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice maxOccurs="unbounded">
     *         &lt;element name="Item" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;simpleContent>
     *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *                 &lt;attribute name="Type" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/extension>
     *             &lt;/simpleContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="PropertyType" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/choice>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "itemOrPropertyType"
    })
    public static class PledgedProperty {

        @XmlElements({
            @XmlElement(name = "PropertyType", type = String.class),
            @XmlElement(name = "Item", type = SparkPledgeByVIN.PledgedProperty.Item.class)
        })
        protected List<Object> itemOrPropertyType;

        /**
         * Gets the value of the itemOrPropertyType property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the itemOrPropertyType property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getItemOrPropertyType().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * {@link SparkPledgeByVIN.PledgedProperty.Item }
         * 
         * 
         */
        public List<Object> getItemOrPropertyType() {
            if (itemOrPropertyType == null) {
                itemOrPropertyType = new ArrayList<Object>();
            }
            return this.itemOrPropertyType;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;simpleContent>
         *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
         *       &lt;attribute name="Type" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/extension>
         *   &lt;/simpleContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class Item {

            @XmlValue
            protected String value;
            @XmlAttribute(name = "Type")
            protected String type;

            /**
             * Gets the value of the value property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setValue(String value) {
                this.value = value;
            }

            /**
             * Gets the value of the type property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getType() {
                return type;
            }

            /**
             * Sets the value of the type property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setType(String value) {
                this.type = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Participant" type="{}sparkPledgeParticipant" maxOccurs="unbounded" minOccurs="0"/>
     *         &lt;element name="ParticipantId" type="{http://www.w3.org/2001/XMLSchema}int" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "participant",
        "participantId"
    })
    public static class Pledgees {

        @XmlElement(name = "Participant")
        protected List<SparkPledgeParticipant> participant;
        @XmlElement(name = "ParticipantId", type = Integer.class)
        protected List<Integer> participantId;

        /**
         * Gets the value of the participant property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the participant property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getParticipant().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link SparkPledgeParticipant }
         * 
         * 
         */
        public List<SparkPledgeParticipant> getParticipant() {
            if (participant == null) {
                participant = new ArrayList<SparkPledgeParticipant>();
            }
            return this.participant;
        }

        /**
         * Gets the value of the participantId property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the participantId property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getParticipantId().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Integer }
         * 
         * 
         */
        public List<Integer> getParticipantId() {
            if (participantId == null) {
                participantId = new ArrayList<Integer>();
            }
            return this.participantId;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Participant" type="{}sparkPledgeParticipant" maxOccurs="unbounded" minOccurs="0"/>
     *         &lt;element name="ParticipantId" type="{http://www.w3.org/2001/XMLSchema}int" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "participant",
        "participantId"
    })
    public static class Pledgers {

        @XmlElement(name = "Participant")
        protected List<SparkPledgeParticipant> participant;
        @XmlElement(name = "ParticipantId", type = Integer.class)
        protected List<Integer> participantId;

        /**
         * Gets the value of the participant property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the participant property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getParticipant().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link SparkPledgeParticipant }
         * 
         * 
         */
        public List<SparkPledgeParticipant> getParticipant() {
            if (participant == null) {
                participant = new ArrayList<SparkPledgeParticipant>();
            }
            return this.participant;
        }

        /**
         * Gets the value of the participantId property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the participantId property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getParticipantId().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Integer }
         * 
         * 
         */
        public List<Integer> getParticipantId() {
            if (participantId == null) {
                participantId = new ArrayList<Integer>();
            }
            return this.participantId;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *       &lt;attribute name="Date" type="{http://www.w3.org/2001/XMLSchema}date" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class StopReason {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "Date")
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar date;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the date property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getDate() {
            return date;
        }

        /**
         * Sets the value of the date property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setDate(XMLGregorianCalendar value) {
            this.date = value;
        }

    }

}
