//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-27 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.03.04 at 11:42:46 AM MSK 
//


package ru.creditregistry._2010.webservice.singleformat.response;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * Сводные данные об арбитражных делах за год
 * 
 * <p>Java class for sparkArbitrationSummaryByYear complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="sparkArbitrationSummaryByYear">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Plaintiff">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="CasesNumber" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                 &lt;attribute name="Sum" use="required" type="{}sparkMyDecimal" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Defendant">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="CasesNumber" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *                 &lt;attribute name="Sum" use="required" type="{}sparkMyDecimal" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="ThirdOrOtherPerson">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="CasesNumber" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="Year" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "sparkArbitrationSummaryByYear", propOrder = {
    "plaintiff",
    "defendant",
    "thirdOrOtherPerson"
})
public class SparkArbitrationSummaryByYear {

    @XmlElement(name = "Plaintiff", required = true)
    protected SparkArbitrationSummaryByYear.Plaintiff plaintiff;
    @XmlElement(name = "Defendant", required = true)
    protected SparkArbitrationSummaryByYear.Defendant defendant;
    @XmlElement(name = "ThirdOrOtherPerson", required = true)
    protected SparkArbitrationSummaryByYear.ThirdOrOtherPerson thirdOrOtherPerson;
    @XmlAttribute(name = "Year", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String year;

    /**
     * Gets the value of the plaintiff property.
     * 
     * @return
     *     possible object is
     *     {@link SparkArbitrationSummaryByYear.Plaintiff }
     *     
     */
    public SparkArbitrationSummaryByYear.Plaintiff getPlaintiff() {
        return plaintiff;
    }

    /**
     * Sets the value of the plaintiff property.
     * 
     * @param value
     *     allowed object is
     *     {@link SparkArbitrationSummaryByYear.Plaintiff }
     *     
     */
    public void setPlaintiff(SparkArbitrationSummaryByYear.Plaintiff value) {
        this.plaintiff = value;
    }

    /**
     * Gets the value of the defendant property.
     * 
     * @return
     *     possible object is
     *     {@link SparkArbitrationSummaryByYear.Defendant }
     *     
     */
    public SparkArbitrationSummaryByYear.Defendant getDefendant() {
        return defendant;
    }

    /**
     * Sets the value of the defendant property.
     * 
     * @param value
     *     allowed object is
     *     {@link SparkArbitrationSummaryByYear.Defendant }
     *     
     */
    public void setDefendant(SparkArbitrationSummaryByYear.Defendant value) {
        this.defendant = value;
    }

    /**
     * Gets the value of the thirdOrOtherPerson property.
     * 
     * @return
     *     possible object is
     *     {@link SparkArbitrationSummaryByYear.ThirdOrOtherPerson }
     *     
     */
    public SparkArbitrationSummaryByYear.ThirdOrOtherPerson getThirdOrOtherPerson() {
        return thirdOrOtherPerson;
    }

    /**
     * Sets the value of the thirdOrOtherPerson property.
     * 
     * @param value
     *     allowed object is
     *     {@link SparkArbitrationSummaryByYear.ThirdOrOtherPerson }
     *     
     */
    public void setThirdOrOtherPerson(SparkArbitrationSummaryByYear.ThirdOrOtherPerson value) {
        this.thirdOrOtherPerson = value;
    }

    /**
     * Gets the value of the year property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getYear() {
        return year;
    }

    /**
     * Sets the value of the year property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setYear(String value) {
        this.year = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="CasesNumber" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
     *       &lt;attribute name="Sum" use="required" type="{}sparkMyDecimal" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Defendant {

        @XmlAttribute(name = "CasesNumber", required = true)
        protected int casesNumber;
        @XmlAttribute(name = "Sum", required = true)
        protected String sum;

        /**
         * Gets the value of the casesNumber property.
         * 
         */
        public int getCasesNumber() {
            return casesNumber;
        }

        /**
         * Sets the value of the casesNumber property.
         * 
         */
        public void setCasesNumber(int value) {
            this.casesNumber = value;
        }

        /**
         * Gets the value of the sum property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSum() {
            return sum;
        }

        /**
         * Sets the value of the sum property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSum(String value) {
            this.sum = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="CasesNumber" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
     *       &lt;attribute name="Sum" use="required" type="{}sparkMyDecimal" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Plaintiff {

        @XmlAttribute(name = "CasesNumber", required = true)
        protected int casesNumber;
        @XmlAttribute(name = "Sum", required = true)
        protected String sum;

        /**
         * Gets the value of the casesNumber property.
         * 
         */
        public int getCasesNumber() {
            return casesNumber;
        }

        /**
         * Sets the value of the casesNumber property.
         * 
         */
        public void setCasesNumber(int value) {
            this.casesNumber = value;
        }

        /**
         * Gets the value of the sum property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSum() {
            return sum;
        }

        /**
         * Sets the value of the sum property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSum(String value) {
            this.sum = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="CasesNumber" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class ThirdOrOtherPerson {

        @XmlAttribute(name = "CasesNumber", required = true)
        protected int casesNumber;

        /**
         * Gets the value of the casesNumber property.
         * 
         */
        public int getCasesNumber() {
            return casesNumber;
        }

        /**
         * Sets the value of the casesNumber property.
         * 
         */
        public void setCasesNumber(int value) {
            this.casesNumber = value;
        }

    }

}
