
package ru.akbars.integro.creapp.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.4.1
 * Wed Aug 22 18:43:50 MSK 2018
 * Generated source version: 2.4.1
 */

@XmlRootElement(name = "executeRequest", namespace = "http://creapp.integro.akbars.ru/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "executeRequest", namespace = "http://creapp.integro.akbars.ru/")

public class ExecuteRequest {

    @XmlElement(name = "requestData")
    private ru.akbars.integro.creapp.RequestData requestData;

	public ru.akbars.integro.creapp.RequestData getRequestData()
	{
		return requestData;
	}

	public void setRequestData(ru.akbars.integro.creapp.RequestData requestData)
	{
		this.requestData = requestData;
	}

    

}

